### ISSUE TITLE
convert list to a Sx

### ISSUE THREAD

**Issue by catta134** [adbuerger/casadi-examples#1]
i want to do this 
uf1 = VectProd([(q[2]-q[0]),(q[3]-q[1]),0],[0,0,tau[1]])/sign(horzcat(*VectProd([(q[2]-q[0]),(q[3]-q[1]),0],[0,0,tau[1]])))
but I have this error
 uf1 = VectProd([(q[2]-q[0]),(q[3]-q[1]),0],[0,0,tau[1]])/sign(horzcat(*VectProd([(q[2]-q[0]),(q[3]-q[1]),0],[0,0,tau[1]])))
TypeError: unsupported operand type(s) for /: 'list' and 'MX'..
some can help me, there is a way to convert my vector v= [x,y,z] into variablie SX or MX..
thanks for all..

**Comment by adbuerger** [comment]
Hello catta134,

I cannot see the vector `v` in your code, but I assume it contains some number of floats. The problem with the list is that it contains no information on the dimensions of the object, which an array does.

The SX and MX variables can be used for symbolic values only. What you need is a DM (formerly called DMatrix) from CasADi, or a NumPy array. To convert your vector `v` to a NumPy array, you can use

    v_array = numpy.asarray(v)

which you can then use in combination with CasADi objects.

Hope this helps! Also, consider the CasADi forum at https://groups.google.com/forum/#!forum/casadi-users for further questions of this kind so more people can later benefit from the answers there, and have a look at the video tutorial on CasADi at https://www.youtube.com/watch?v=cOglZbSstjQ

**Comment by adbuerger** [comment]
Oh, looking at it once more, I think I got your question wrong:

The function `VecProd()` probably returns a list, which you then divide by an MX produces by `sign()`. Probably it helps to replace

    VectProd([(q[2]-q[0]),(q[3]-q[1]),0],[0,0,tau[1]])

with

   VectProd([(q[2]-q[0]),(q[3]-q[1]),0],[0,0,tau[1]])[0]

which is selecting the returned MX from the list. Does this work for you?

**Comment by catta134** [comment]
yes, thanks a lot..

**Comment by adbuerger** [comment]
No problem! I'm glad I could help!
