### ISSUE TITLE
casadi error when define a new MX

### ISSUE THREAD

**Issue by catta134** [adbuerger/casadi-examples#2]
Qds = struct_symSX(["qd0", "qd1", "qd2"])

cs = struct_MX([
                    entry("Qds", struct = Qds, repeat = N+1)
                ])
the error is:
Traceback (most recent call last):
  File "impl_nc_prr.py", line 584, in <module>
    entry("Qds", struct = Qds, repeat = N+1)
  File "/usr/lib/python2.7/dist-packages/casadi/tools/structure.py", line 1067, in __init__
    raise Exception("struct_MX does only accept entries with an 'expr' argument.")
Exception: struct_MX does only accept entries with an 'expr' argument.

but I can't understand what is the problem, someone could help me. (write in python code by casadi, and casadi.tools)

**Comment by adbuerger** [comment]
Maybe you want to use

    Qds = struct_symSX(["qd0", "qd1", "qd2"])

    cs = struct_symMX([
        entry("Qds", struct = Qds, repeat = N+1)
    ])

which can be used to repeat `Qds`. Does this help?

Again, consider the CasADi forum at https://groups.google.com/forum/#!forum/casadi-users for further questions of this kind so more people can later benefit from the answers there.
